### ISSUE TITLE
Try to make bond drawing asynchronous

### ISSUE THREAD

**Issue by mjtadema** [mjtadema/pycg_bonds#14]
The `fetch` command in [pymol](https://pymolwiki.org/index.php/Fetch) has an `async` option.
We might be able to use this to do bond drawing in the background so pymol doesn't freeze, especially for larger systems with lots of molecules.

**Comment by brisvag** [comment]
I tried using `pymol.cmd.async_`, but it didn't work the way I hoped. You can try it out if you want, maybe you're luckier, but I think we should close this and just hope in a quick upstream fix.

**Comment by brisvag** [comment]
I will close this, since #26 will basically do the same thing but better.
