### ISSUE TITLE
add the setup.py stuff and make it an actual pip thing

### ISSUE THREAD

**Issue by mjtadema** [mjtadema/pycg_bonds#25]
I'm trying to use it as a module, and I'm having problems. I need to fix some stuff probably, so wait with the merge!

EDIT: also, this might be a good place to add the setup.py stuff and make it an actual pip thing. Could you do it?

_Originally posted by @brisvag in https://github.com/mjtadema/pycg_bonds/pull/24#issuecomment-503971047_

**Comment by mjtadema** [comment]
Setup.py was added in #27

**Comment by brisvag** [comment]
Actually still need to add.

**Comment by brisvag** [comment]
Now closed for real by #31.
